name: Release sg-core
permissions:
  contents: read

on:
  release:
    types:
      - released
      - prereleased

env:
  imageregistry: 'quay.io'
  imagenamespace: ${{ secrets.IMAGENAMESPACE || secrets.QUAY_USERNAME }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Tag image
      uses: tinact/docker.image-retag@684702232e2a3c29b4e5ca25d7d80f927d255c64 # 1.0.3
      with:
        image_name: ${{ env.imagenamespace }}/sg-core
        image_old_tag: ${{ github.sha }}
        image_new_tag: ${{ github.event.release.tag_name }}
        registry: ${{ env.imageregistry }}
        registry_username: ${{ secrets.QUAY_USERNAME }}
        registry_password: ${{ secrets.QUAY_PASSWORD }}
